### ISSUE TITLE
The knife should be applied automatically immediately

### ISSUE THREAD

**Issue by Ekrons** [umiyuki/Artstage-Issues#19]
We don't have to confirm the cuts when finished. It should be possible to undo every cut, and this is enough to not confirm them in the end.
Now, if we cut, and choose another tool, the cuts disappear. 
The cut should be completed immediately, and the exit from knife should be done when the user has selected another tool.

**Comment by Ekrons** [comment]
I beg you to make this opportunity, since a lot of problems will be solved with the speed and convenience of editing the wire.

**Comment by umiyuki** [comment]
Hello Ekrons.
You will still need the confirmation function. I think I can not start another cut if I can not confirm the cut.

**Comment by Ekrons** [comment]
Hello umiyuki.
Well, so be it, but otherwise nothing changes.
- The knife must always be confirmed automatically.
- The ability to undo each cut.
- The choice of another tool does not cancel the cuts made.

**Comment by umiyuki** [comment]
@Ekrons 
This request is not yet implemented.
Why did you close this? Because the function became unnecessary for you? Please close after writing the reason.

**Comment by Ekrons** [comment]
@umiyuki  Since such inconsequential things as “transparency of controllers” or “Floor Boundaries Off” are already being implemented, I considered that no one would deal with this feature anymore, closed the issue, so as not to distract from more important and complex features, such as #5, #17 and #41.
In fact, the knife works well. With this improvement, of course, it would be faster and more convenient to work, but I have already lost hope.
By the way, this is not the only feature that I want to keep silent about for the sake of other more significant ones.
I wanted to ask to make HDR and lighting as in the Kodon, and add various shaders. https://www.youtube.com/watch?v=tWQpcOL84zE
But I don't ask, since the visual component is the last thing that needs to be implemented after the modeling tools.

**Comment by umiyuki** [comment]
I understand this clearly, but your actions and remarks have no respect for others and no sincerity.
This is a childish behavior that frustrates others.
There has been ample opportunity to change behavior. But you do not change.
Obviously, the purpose of your remarks has shifted from improving the application to scolding the developer.
I came up with the idea that I had to ban you.
Perhaps other people will also think that my judgment is reasonable if they read your remarks.
Because your remarks stand out on this board and lack common sense.
Unfortunately, it is unavoidable for the healthy development of the application.
