### ISSUE TITLE
Dissolve edges. vertices.

### ISSUE THREAD

**Issue by umiyuki** [umiyuki/Artstage-Issues#3]
Posted from steam thread board.
https://steamcommunity.com/app/523050/discussions/0/1770385542779403272/

**Comment by Ekrons** [comment]
If someone doesn't know how it works:
![01 Dissolve Edges](https://user-images.githubusercontent.com/50044554/56848935-9efaf080-68f6-11e9-8f78-491a5130b1ee.gif)
![02 Dissolve Edges 2](https://user-images.githubusercontent.com/50044554/56848937-a1f5e100-68f6-11e9-9279-7af19b629beb.gif)

**Comment by Ekrons** [comment]
As it turned out, this feature is already implemented in Artstage. Just the author of the program does not distinguish between "delete" and "dissolve". Now the removal tool produces the dissolving of vertices and edges. Then the question is, what about the tool for removing vertices and edges?

And yet, when we dissolve the edges, we cannot select edge loop to dissolve it.

**Comment by umiyuki** [comment]
This issue will closes if your problem is solved.
You may want to go through the tutorial video before suggesting a request.

I don't know the grounds for you to be concerned that the terms in Artstage and Blender do not match exactly.
Delete edges and delete points works like this in Maya.
When you delete an edge in Blender, it actually removes the face that contains the edge, not the edge.
