### ISSUE TITLE
Valve Index controllers support

### ISSUE THREAD

**Issue by Ekrons** [umiyuki/Artstage-Issues#34]
The program should support modern controllers, which are currently the best in the world together with Pimax controllers.

**Comment by umiyuki** [comment]
Do you have Knuckles?

**Comment by Ekrons** [comment]
- I sold my CV1.
- Bought Vive for base stations.
I don't see convenience in Vive controllers, in any way I will buy knuckles or Pimax controllers.

With Pimax everything will be difficult. They have many variations of the right and left controller.
If it is difficult to support the controllers, do not do it yet. Since no one needs their support yet.

**Comment by Ekrons** [comment]
It's interesting...
![Image 2019, 06, 19, 14, 02, 09](https://user-images.githubusercontent.com/50044554/59760266-955c8c00-929a-11e9-8053-c1aecd593b54.png)

**Comment by umiyuki** [comment]
Certainly this seems to be added automatically.
However, this means Index HMD support, not Index Controller support.

Index is also sold by HMD only or controller only.
That is, there are also combinations of Index HMD and Vive Controller, Vive HMD and Index Controller, etc.
In any case, this notation may mislead the user.

Artstage automatically switched the controller operation method by identifying the HMD.
However, even if the user is using Vive HMD, I realized that it might be possible to use Index Controller instead of Vive Controller.
I plan to introduce an option to manually specify the controller type in Artstage.
If you use Index Controller, you can specify the controller type as Oculus Touch and you can do the same operation as Touch. (Controller in VR is also displayed as Touch)

**Comment by Ekrons** [comment]
It will be nice.
I'm worried about what will happen to the grips. Index has a button with pressure levels instead grips. Will grip on Index controllers even work at Artstage?

**Comment by umiyuki** [comment]
The grip of the index controller is a pressure sensor, not a button, and is obtained as an analog value.
Perhaps you can set the key configuration of SteamVR to determine how strongly you grasp it when you “grip” it.

**Comment by umiyuki** [comment]
In the current version of Artstage, a function to manually specify the controller type is implemented. If you specify the controller type as OculusTouch, you should be able to use the Index controller.
Close this issue, but if you still have problems, reopen it.
