### ISSUE TITLE
The "knife" tool too badly magnetizes to edges and vertices.

### ISSUE THREAD

**Issue by Ekrons** [umiyuki/Artstage-Issues#40]
It happens, you need 20 seconds to try to cut the one edge and don't miss.

**Comment by umiyuki** [comment]
I may eventually improve it, but with the current version you can avoid the extra snap by making the cursor sphere smaller (or make the model bigger).

**Comment by Ekrons** [comment]
Yes, increasing the model helps, but it takes a lot of time if we need to cut it often. 
It would be better if the knife worked the other way around: in the normal state, it magnetizes well to the edges and vertices, and badly to the faces, and when the model is enlarged, it magnetizes better to the faces.

**Comment by MarkMironov** [comment]
I also came across this. The knife sticks better to the faces than to the edges. It should be the other way around.

**Comment by MarkMironov** [comment]
Knife now works very poorly in this regard.

@umiyuki , please remake the knife so that it sticks better to the edges and vertices. 
This is some kind of horror, I can’t get to some vertices at all. Even scaling does not help. I even have to use the tools from the "Action" tab instead of the functions that the knife should perform.

**Comment by umiyuki** [comment]
Sure, I'm frustrated with the knife snap when using Artstage myself too.
The reason is that the knife needs to be able to snap to all of any vertex, edge, or face.
The solution I am thinking of is just to be able to select the snap target in the tool config. In other words, you can do so when you only want to snap to faces.

**Comment by MarkMironov** [comment]
@umiyuki this will be great)

**Comment by umiyuki** [comment]
This feature was implemented in Ver0.8.5.

**Comment by umiyuki** [comment]
Close this issue.
