### ISSUE TITLE
Proportional editing.

### ISSUE THREAD

**Issue by umiyuki** [umiyuki/Artstage-Issues#5]
Posted from steam thread board.
https://steamcommunity.com/app/523050/discussions/0/1770385542779403272/

**Comment by Ekrons** [comment]
If someone doesn't know how it works:
![03 Proportional Editing](https://user-images.githubusercontent.com/50044554/56847806-378a7400-68e9-11e9-936a-1e1ec23c6b50.gif)

**Comment by Aitolda** [comment]
I can't seem to upvote this one, but I agree.

**Comment by umiyuki** [comment]
> I can't seem to upvote this one, but I agree.

Hi, Aitoda.
You can vote like this.
![vote](https://user-images.githubusercontent.com/6958622/57180495-e91a3e00-6ec3-11e9-8935-2c906c09bfb1.jpg)

**Comment by MarkMironov** [comment]
I looked at the remaining issues and it seems that this is the most necessary function that remains to be implemented. 
Since it is often necessary to smoothly shift a large area, but moving each vertex is too long and difficult, and moving each vertex can slightly distort the original shape.
Since there will be no sculpting brush, then this function would be a worthy replacement.

**Comment by MarkMironov** [comment]
@umiyuki Thanks for the proportional editing! It is very useful. And thanks for its yellow color)

**Comment by Aitolda** [comment]
Woo!

**Comment by umiyuki** [comment]
Proportional editing was implemented in ver0.9.1. Close this issue.
